accounts/urls.py
from django.urls import path
from .views import *

app_name = "accounts"

urlpatterns = [
    path("login/", login_view, name="login"),
    path("register/", register_view, name="register"),
    path("logout/", logout_view, name="logout"),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from home.views import home_view
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", home_view, name="home"),
    path("post/", include("post.urls")),
    path("accounts/", include("accounts.urls")),
]

# media dosyaları url tanımlaması
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from .views import *

# url lere uygulama ismi üzerinden erişmek için
app_name = "post"

urlpatterns = [
    # statik url ler
    path("index/", post_index, name="index"),
    path("create/", post_create, name="create"),

    # dinamik url ler
    path("<str:slug>/detail/", post_detail, name="detail"),
    path("<str:slug>/delete/", post_delete, name="delete"),
    path("<str:slug>/update/", post_update, name="update"),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
# Create your views here.

def home_view(request):
    if request.user.is_authenticated:
        context = {
            "isim": request.user.username
        }
    else:
        context = {
            "isim": "Misafir"
        }
    return render(request, "home.html", context=context)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    

    {# block a varsayılan değer atadık. Django Blog #}
    <title>{% block title %}Django Blog{% endblock title %}</title>
</head>
<body>
    {% include 'header.html' %}

    {% include 'messages.html' %}

    {% block body %}

    {% endblock body %}

    <script src="{% static 'js/jquery-3.3.1.min.js'%}"></script>
    <script src="{% static 'js/bootstrap.min.js'%}"></script>
</body>
</html>

templates/header.html
<!-- Navbar Start -->
<nav class="navbar navbar-inverse" role="banner">
    <div class="container">

        <div class="navbar-header">

            <!-- Telefon ekranları için menü butonu -->
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <!-- İsim Soyisim veya Marka İsmi -->
            <a href="{% url 'home' %}" class="navbar-brand">Django Dersleri</a>
        </div>

        <nav class="collapse navbar-collapse" role="navigation">

            <!-- Arama Çubuğu -->
            <form class="navbar-form navbar-left" role="search" method="GET" action="">
                <div class="input-group">
                    <input class="form-control" type="text" name="q" placeholder="Search on blog" value="{{ request.GET.q }}" >
                    <span class="input-group-btn">
                        <input class="btn btn-default" type="submit" value="Ara">
                    </span>
                </div>
            </form>

            <!-- Temel Sayfalar -->
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'home' %}">Anasayfa</a></li>
                {% if request.user.is_authenticated %}
                    <li><a href="{% url 'post:create' %}">Yazı Ekle</a></li>
                {% endif %}
                <li><a href="{% url 'post:index'%}">Blog</a></li>
                <li><a href="#">Hakkımda</a></li>
                <li><a href="#">İletişim</a></li>
                {% if not request.user.is_authenticated %}
                    <li><a href="{% url 'accounts:register' %}">Üye ol</a></li>
                    <li><a href="{% url 'accounts:login' %}">Giriş</a></li>
                {% else %}
                    <li><a href="{% url 'accounts:logout' %}">Çıkış</a></li>
                {% endif %} 
            </ul>

        </nav>

    </div>
</nav>

templates/home.html
{% extends 'base.html' %}


{# block.super üst templatedeki varsayılan değer demek. #}
{% block title %}Anasayfa - {{block.super}}{% endblock title %}
    

{% block body %}

    <div class="container">
        <div class="row">
        </div>
    </div>

{% endblock body %}

templates/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            {{ message }}.
        </div>
    {% endfor %}
{% endif%}